name: yapster
description: "A Flutter application with GetX architecture."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  shared_preferences: ^2.2.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  intl: ^0.20.2
  supabase_flutter: ^2.9.0
  google_sign_in: ^6.3.0
  flutter_dotenv: ^5.2.1
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_easyloading: ^3.0.5
  path_provider: ^2.1.2
  connectivity_plus: ^6.1.4
  flutter_cache_manager: ^3.3.1
  encrypt: ^5.0.3
  crypto: ^3.0.3
  flutter_keyboard_visibility: ^6.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/fonts/

  # fonts:
  #   - family: Poppins
  #     fonts:
  # - asset: assets/fonts/Poppins-Regular.ttf
  # - asset: assets/fonts/Poppins-Medium.ttf
  #   weight: 500
  # - asset: assets/fonts/Poppins-SemiBold.ttf
  #   weight: 600
  # - asset: assets/fonts/Poppins-Bold.ttf
  #   weight: 700
