import 'dart:io';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:image_picker/image_picker.dart';
import 'package:yapster/app/core/utils/supabase_service.dart';
import 'package:yapster/app/data/repositories/post_repository.dart';
import 'package:yapster/app/data/models/post_model.dart';

class CreatePostController extends GetxController {
  final SupabaseService _supabase = Get.find<SupabaseService>();
  final PostRepository _postRepository = Get.find<PostRepository>();
  final ImagePicker _picker = ImagePicker();

  // Text controller for post content
  final TextEditingController contentController = TextEditingController();

  // Observable variables
  final RxList<File> selectedImages = <File>[].obs;
  final RxBool isLoading = false.obs;
  final RxString postType = 'text'.obs;
  final RxBool canPost = false.obs;

  @override
  void onInit() {
    super.onInit();
    // Listen to content changes to enable/disable post button
    contentController.addListener(_updateCanPost);
  }

  @override
  void onClose() {
    contentController.dispose();
    super.onClose();
  }

  void _updateCanPost() {
    canPost.value =
        contentController.text.trim().isNotEmpty || selectedImages.isNotEmpty;
  }

  /// Pick images from gallery
  Future<void> pickImages() async {
    try {
      final List<XFile> images = await _picker.pickMultiImage(
        maxWidth: 1080,
        maxHeight: 1080,
        imageQuality: 85,
      );

      if (images.isNotEmpty) {
        // Limit to 3 images maximum
        final imagesToAdd = images.take(3 - selectedImages.length).toList();

        for (final image in imagesToAdd) {
          selectedImages.add(File(image.path));
        }

        if (selectedImages.isNotEmpty) {
          postType.value = 'image';
        }

        _updateCanPost();
      }
    } catch (e) {
      print('Error picking images: $e');
      Get.snackbar(
        'Error',
        'Failed to pick images',
        snackPosition: SnackPosition.BOTTOM,
      );
    }
  }

  /// Remove image at index
  void removeImage(int index) {
    if (index >= 0 && index < selectedImages.length) {
      selectedImages.removeAt(index);

      if (selectedImages.isEmpty && contentController.text.trim().isNotEmpty) {
        postType.value = 'text';
      } else if (selectedImages.isEmpty &&
          contentController.text.trim().isEmpty) {
        postType.value = 'text';
      }

      _updateCanPost();
    }
  }

  /// Create and publish post
  Future<void> createPost() async {
    if (!canPost.value) return;

    try {
      isLoading.value = true;

      final currentUser = _supabase.client.auth.currentUser;
      if (currentUser == null) {
        Get.snackbar('Error', 'User not authenticated');
        return;
      }

      // Create post model
      final post = PostModel(
        id: '', // Will be generated by database
        userId: currentUser.id,
        content: contentController.text.trim(),
        postType: postType.value,
        metadata: {}, // Will be updated with image URLs after upload
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      // Create post with images
      final postId = await _postRepository.createPostWithImages(
        post,
        selectedImages.toList(),
      );

      if (postId != null) {
        Get.snackbar(
          'Success',
          'Post created successfully!',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.green,
          colorText: Colors.white,
        );

        // Clear form
        _clearForm();

        // Navigate back to home
        Get.back();
      } else {
        Get.snackbar(
          'Error',
          'Failed to create post',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red,
          colorText: Colors.white,
        );
      }
    } catch (e) {
      print('Error creating post: $e');
      Get.snackbar(
        'Error',
        'Failed to create post: $e',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    } finally {
      isLoading.value = false;
    }
  }

  /// Clear form data
  void _clearForm() {
    contentController.clear();
    selectedImages.clear();
    postType.value = 'text';
    canPost.value = false;
  }

  /// Get image layout for UI
  String getImageLayout() {
    switch (selectedImages.length) {
      case 1:
        return 'single';
      case 2:
        return 'double';
      case 3:
        return 'triple';
      default:
        return 'none';
    }
  }
}
